# Deploy Standard Logic App
    
 trigger:
 - master
    
 pool:
   vmImage: 'windows-latest'
    
 variables:
   buildPlatform: 'Any CPU'
   buildConfiguration: 'Release'
    
 jobs:
 - job: logic_app_build
   displayName: 'Build and publish logic app'
   steps:
   - task: CopyFiles@2
     displayName: 'Create project folder'
     inputs:
       SourceFolder: '$(System.DefaultWorkingDirectory)'
       Contents: |
         **
       TargetFolder: 'project_output'
    
   - task: ArchiveFiles@2
     displayName: 'Create project zip'
     inputs:
       rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output'
       includeRootFolder: false
       archiveType: 'zip'
       archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
       replaceExistingArchive: true
    
   - task: AzureFunctionApp@1
     displayName: 'Deploy logic app workflows'
     inputs:
       azureSubscription: 'SS'
       appType: 'workflowapp'
       appName: 'S-logApp-290722'
       package: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
       deploymentMethod: 'zipDeploy'